version: '3.8'

services:
  backend:
    image: jahua/chatbot-backend:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=3.76.40.121
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=336699
      - POSTGRES_DB=trip_dw
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - chroma
    networks:
      - chatbot_network

  frontend:
    image: jahua/chatbot-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - static_volume:/app/static:ro
    environment:
      - POSTGRES_HOST=3.76.40.121
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=336699
      - POSTGRES_DB=trip_dw
      - API_URL=http://backend:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
    networks:
      - chatbot_network

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/chroma
    ports:
      - "8006:8000"
    environment:
      - ALLOW_RESET=true
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge

volumes:
  index_data:
    driver: local
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/docker-apps/chatbot/static
      o: bind 